config/routes.rb
Rails.application.routes.draw do

  resources :wikis
  resources :collaborators, only: [:create, :destroy]
  
  get 'public_wikis' => 'wikis#public_wikis', :as => 'public_wikis'

  devise_for :users

  resources :charges, only: [:new, :create]

  root 'welcome#index'

  post 'charges/downgrade' => 'charges#downgrade', :as => 'downgrade'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :wiki
  belongs_to :user
  
  def self.available(wiki,current_user)
    # Anyone who is not the wiki owner
    possible_collaborators = User.all.where.not(id: current_user.id)
    # Does this wiki already have collaborators
    already_taken = wiki.collaborators.map { |collaborator| User.find_by_id(collaborator.user_id) }
    possible_collaborators - already_taken
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :wikis, dependent: :destroy

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:member)
  end

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  
  def self.downgrade(current_user)
    current_user.wikis.each do | wiki |
      wiki.private = false
      wiki.save
    end
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  
  def require_login
    unless current_user
      flash[:alert] = "You must be logged in to do that"
      redirect_to new_user_session_path
    end
  end
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
     # Creates a Stripe Customer object, for associating with the charge
     customer = Stripe::Customer.create(
       email: current_user.email,
       card: params[:stripeToken]
     )
   
     # Charge the user with stripe
     charge = Stripe::Charge.create(
       customer: customer.id, # Note -- this is NOT the user_id in your app
       amount: Amount.default,
       description: "Cogniden Premium Membership - #{current_user.email}",
       currency: 'usd'
     )
   
     flash[:notice] = "Thank you for the payment, #{current_user.email}. You're now a premium member!"
     current_user.add_role :premium
     redirect_to wikis_path
   
     # Rescue Stripe Errors
     rescue Stripe::CardError => e
       flash[:alert] = e.message
       redirect_to new_charge_path
  end
  
  def new
     @stripe_btn_data = {
       key: "#{ Rails.configuration.stripe[:publishable_key] }",
       description: "Cogniden Premium Membership - #{current_user.email}",
       amount: Amount.default
     }
  end
  
  def downgrade
    current_user.remove_role :premium
    Wiki.downgrade(current_user)
    flash[:notice] = "Awww! You've been downgraded to a standard user.Your private wikis will be made public!"
    redirect_to root_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  
  def create
    @collaborator = Collaborator.new(collaborator_params)
    
    if @collaborator.save
      flash[:notice] = "\"#{@collaborator.user.email}\" has been successfully added.Yay!"
      redirect_to Wiki.find_by(params[:collaborator][:wiki_id])
    else
      flash.now[:alert] = "Bummer!There was an error adding the collaborator \"#{@collaborator.user.email}\" :( .Please try again."
      redirect_to Wiki.find_by(params[:collaborator][:wiki_id])
    end  
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    
    if @collaborator.destroy
      flash[:notice] = "\"#{@collaborator.user.email}\" was successfully removed as collaborator."
      redirect_to @collaborator.wiki
    else
      flash[:alert] = "There was an error trying to remove the collaborator \"#{@collaborator.user.email}\".Please try again later."
      redirect_to @collaborator.wiki   
    end
  end
  
  private
  
  def collaborator_params
    params.require(:collaborator).permit(:wiki_id, :user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def index
  end

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  
  before_action :require_login
  
  def index
    @wikis = policy_scope(Wiki)
  end
  
  def public_wikis
    @wikis = Wiki.all
  end
    

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
  end
  
  def create
    @wiki = Wiki.new(wiki_params)
    
    authorize @wiki
    @wiki.user_id = params[:wiki][:user]||= current_user.id
   
    if @wiki.save
      flash[:notice] = "Your wiki has been successfully created.Yay!"
      redirect_to @wiki
    else
      flash.now[:alert] = "Bummer!There was an error creating the wiki :( .Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    
    @allcollaborators = Collaborator.available(@wiki,  current_user)
  end
  
  def update
    @wiki = Wiki.find(params[:id])
    
    authorize @wiki
    @wiki.assign_attributes(wiki_params) 
    
    if @wiki.save
      flash[notice] = "Wiki has been successfully updated!"
      redirect_to [@wiki]
    else
      flash.now[:alert] = "Bummer!There was an error trying to save the wiki changes.Please try again later"
      render :edit
    end
  end  
  
  def destroy
    @wiki = Wiki.find(params[:id])
    
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "Bummer!There was an error deleting the wiki.Please try again later"
      render :show
    end
  end
  
  private
  
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
  
end

app/helpers/application_helper.rb
require 'redcarpet'

module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def user_signed_in?
    current_user
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
  def show_wiki?(wiki)
    if wiki.private == true
      (current_user.has_role? :admin) ? true : false
    else
      true
    end
  end
  
  def permit_collaboration?(wiki, current_user)
     (current_user.has_role? :admin) || ((current_user.has_role? :premium) && (wiki.user == current_user))
  end
end

app/views/charges/new.html.erb
 <%= form_tag charges_path do %>
   <h4>Click to upgrade to Premium!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" 
   data-key="<%= @stripe_btn_data[:key] %>" 
   data-amount="<%= @stripe_btn_data[:amount] %>" 
   data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cogniden</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to 'Your wikis', wikis_path %></li>
      <li><%= link_to 'All wikis', public_wikis_path %></li>

      <div class="pull-right user-info">
        <% if user_signed_in? %>
          <div class= "pull-right">
            <%= link_to current_user.email, edit_user_registration_path, :class => 'navbar-link' %>
            </br>
            <% if current_user.has_role? :premium %>
              Premium User |  <%= link_to "Downgrade", downgrade_path, method: :post %>
            <% else %>  
              Standard User |  <%= link_to "Upgrade", new_charge_path %>
            <% end %>
            </br>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          </div>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
   <%= yield %>
  </div>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
  <div class="row">
    <h1 class="text-center">
      Welcome to Cogniden!
    </h1>
  </div>
  <div class="row">
    <h3 class="text-center">
      A place to create,share and collaborate awesome wikis.
    </h3>
  </div>
  <% unless user_signed_in? %>
    <div class="row">
      <h2 class="text-center">
          <%= link_to "Sign up now!", new_user_registration_path, :style => "margin-top: 20px; font-size:16px", class: 'btn btn-success' %>
      </h2>
    </div>
  <% end %>
  

app/views/wikis/_dropdown.html.erb
<%= form_for Collaborator.new do |f| %>
  <%= f.label :add_collaborators, :style => "margin-top: 10px; font-size: 17px" %><br>
  <%= f.select(:user_id, @allcollaborators.collect {|w| [w.email, w.id]}, :prompt => 'Select a collaborator', :style => "width: 20px") %><br>
  <%= f.hidden_field :wiki_id, value: @wiki.id %><br>
  <%= f.submit "Add", class: 'btn btn-success btn-sm'%>
<% end %> 

app/views/wikis/_form.html.erb
<div class="col-md-8">
  <%= form_for @wiki do |f| %>
   <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter the wiki's title" %>
   </div>
   <div class="form-group">  
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter the wiki's body" %>
   </div>  
   <% if (current_user.has_role? :admin) || (current_user.has_role? :premium) %>
    <div class="form-group" style="margin-left: 20px;">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
   <% end %>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
  <% end %>
</div>

app/views/wikis/edit.html.erb
 <h1>Edit Wiki</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis:</p>
     <ul>
       <li>Create clear,concise and relevant wikis.</li>
       <li>Ensure that the wiki content is truthful and accurate.</li>
       <li>Omit profane and obscene words.</li>
     </ul>
     <% if permit_collaboration?(@wiki, current_user) %>
       <%= render partial: 'dropdown' %><br>
       <p style="font-size: 17px"><strong>Remove collaborators</strong></p>
       <% @wiki.collaborators.each do |collaborator| %>
         <%= collaborator.user.email %>
         <%= link_to 'Remove', collaborator_path(collaborator), data: { confirm: 'Are you sure?' }, :style => "margin-left: 40px", method: :delete %>
       <% end %>
     <% end %>
   </div>
   <%= render partial: 'wikis/form', locals: { wiki: @wiki } %>
 </div>

app/views/wikis/index.html.erb
<div class="row">
   <div class="col-md-10">
     <h2 class="text-center" style="margin: 20px;"><u>My wikis</u></h2>
     <% if @wikis.count > 0 %>
       <% @wikis.each do |wiki| %>
           <div class="media" style="margin: 40px;">
             <div class="media-body">
               <h4 class="media-heading text-center">
                 <%= link_to wiki.title, wiki %>
               </h4>
             </div>
           </div>
        <% end %>
      <% else %>
         <h3 class="text-center" style="margin: 20px;">You do not have any wikis yet ! Create one using the 'New Wiki' link.</h3> 
      <% end %>
   </div>
   <div class="col-md-2">
     <div style="margin: 20px;">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
      </div>
    </div>
</div>

app/views/wikis/new.html.erb
 <h1>New Wiki</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>Create clear,concise and relevant wikis.</li>
       <li>Ensure that the wiki content is truthful and accurate.</li>
       <li>Omit profane and obscene words.</li>
     </ul>
   </div>
   <%= render partial: 'wikis/form', locals: { wiki: @wiki } %>
 </div>

app/views/wikis/public_wikis.html.erb
<div class="row">
   <div class="col-md-12">
     <h2 class="text-center" style="margin: 20px;"><u>All wikis</u></h2>
     <% if @wikis.count > 0 %>
       <% @wikis.each do |wiki| %>
          <% if show_wiki?(wiki) %>
           <div class="media" style="margin: 40px;">
             <div class="media-body">
               <h4 class="media-heading text-center">
                 <%= link_to wiki.title, wiki %>
               </h4>
             </div>
           </div>
          <% end %>
        <% end %>
      <% else %>
         <h3 class="text-center" style="margin: 20px;">Bummer!There are no wikis available for public view!</h3> 
      <% end %>
   </div>
</div>

app/views/wikis/show.html.erb
  <div class="row">
    <div class="col-md-10">
     <h2 class="text-center">
       <strong><u><%= @wiki.title %></u></strong>
     </h2>
     <div class="text-info" style="margin: 20px; font-size: 18px;">
        <p><%= markdown(@wiki.body) %></p>
     </div>
    </div>
    <div class="col-md-2">
     <div style="margin-top: 25px;">
      <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-success btn-sm' %>
     </div>
     <div style="margin-top: 4px;">
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure you want to delete this wiki?Think long and hard!' } %>
     </div>
     <% if permit_collaboration?(@wiki, current_user) %>
       <div style="margin-top: 20px;">
        <h4><strong>Collaborators</strong></h4>
         <% @wiki.collaborators.each do |collaborator| %>
             <%= link_to collaborator.user.email %><br>
         <% end %>
       </div>
       <div style="margin-top: 20px;">
        <p>Add/Remove Collaborators using 'Edit wiki'.</p>
       </div>
     <% end %>
    </div>
  </div>